# Generated by Django 4.0.5 on 2022-06-03 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default='', max_length=256)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='WineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('producer', models.CharField(default='', max_length=256)),
                ('nation', models.CharField(default='', max_length=256)),
                ('local1', models.CharField(default='', max_length=256)),
                ('local2', models.CharField(default='', max_length=256)),
                ('local3', models.CharField(default='', max_length=256)),
                ('local4', models.CharField(default='', max_length=256)),
                ('varieties1', models.CharField(default='', max_length=256)),
                ('varieties2', models.CharField(default='', max_length=256)),
                ('varieties3', models.CharField(default='', max_length=256)),
                ('varieties4', models.CharField(default='', max_length=256)),
                ('varieties5', models.CharField(default='', max_length=256)),
                ('varieties6', models.CharField(default='', max_length=256)),
                ('varieties7', models.CharField(default='', max_length=256)),
                ('varieties8', models.CharField(default='', max_length=256)),
                ('varieties9', models.CharField(default='', max_length=256)),
                ('varieties10', models.CharField(default='', max_length=256)),
                ('varieties11', models.CharField(default='', max_length=256)),
                ('year', models.IntegerField(default='', max_length=256)),
                ('type', models.CharField(default='', max_length=256)),
                ('degree', models.FloatField(default='', max_length=256)),
                ('sweet', models.IntegerField(default='', max_length=256)),
                ('acidity', models.IntegerField(default='', max_length=256)),
                ('body', models.IntegerField(default='', max_length=256)),
                ('tannin', models.IntegerField(default='', max_length=256)),
                ('price', models.IntegerField(default='', max_length=256)),
                ('av_rating', models.FloatField(default='', max_length=256)),
            ],
            options={
                'db_table': 'wines',
            },
        ),
        migrations.CreateModel(
            name='ReviewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.ratingmodel')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.winemodel')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.AddField(
            model_name='ratingmodel',
            name='wine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine.winemodel'),
        ),
    ]
