# Generated by Django 4.0.5 on 2022-06-09 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winemodel',
            name='wish',
            field=models.ManyToManyField(related_name='wine_wish', to=settings.AUTH_USER_MODEL),
        ),
    ]
