# Generated by Django 4.0.5 on 2022-06-03 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0002_winemodel_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winemodel',
            name='acidity',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='winemodel',
            name='body',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='winemodel',
            name='price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='winemodel',
            name='sweet',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='winemodel',
            name='tannin',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='winemodel',
            name='year',
            field=models.IntegerField(default=''),
        ),
    ]
